---
name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  tarFile: "output-${{ github.job }}-${{ github.run_number }}-${{ github.run_attempt }}.tar.gz"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
        distribution: [ temurin ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        id: setup_build_jdk
        name: Setup Build JDK
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - uses: actions/setup-java@v3
        id: setup_test_jdk
        name: Setup Test JDK
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - id: set_build_jdk
        name: Set the Build JDK
        env:
          JAVA_HOME: ${{ steps.setup_build_jdk.outputs.path }}
        run: |
          echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

      - id: build_distribution
        name: Build the distribution
        env:
          JAVA_HOME: ${{ steps.setup_build_jdk.outputs.path }}
        run: |
          ./mvnw -DskipTests clean install

      - id: set_test_jdk
        name: Set the Test JDK
        env:
          JAVA_HOME: ${{ steps.setup_test_jdk.outputs.path }}
        run: |
          echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

      - id: run_tests
        name: Run the tests
        env:
          JAVA_HOME: ${{ steps.setup_test_jdk.outputs.path }}
        run: |
          ./mvnw surefire:test

      - id: package
        name: Archive the build folder
        if: failure()
        run: |
          FOLDER=$(basename `pwd`)
          cd ..
          tar czf ${{ runner.temp }}/${{ env.tarFile }} --exclude=.git $FOLDER
          mv ${{ runner.temp }}/${{ env.tarFile }} ${{ github.workspace }}

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        id: upload
        name: Upload the build archive to S3
        if: failure()
        with:
          command: cp
          source: ${{ github.workspace }}/${{ env.tarFile }}
          destination: s3://github-action-error-logs/${{ github.repository }}/${{ env.tarFile }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
