---
name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        id: setup_build_jdk
        name: Setup Build JDK
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: |
          ./mvnw clean install
