---
name: CD (Snapshot deployment)

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: sonatype-nexus-snapshots
          server-username: NEXUS_REPO_USER
          server-password: NEXUS_REPO_PASSWORD

      - name: deploy code
        env:
          NEXUS_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
          NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
        run: |
          ./mvnw clean install
